### ISSUE TITLE
initialization 

### ISSUE THREAD

**Issue by dialuser** [isds-neu/PhyCRNet#1]
Hi 
Thanks for sharing the code. What's the rationale for using this uniform range? What do the numbers 3,3,20 represent?

module.weight.data.uniform_(-c*np.sqrt(1 / (3 * 3 * 320)), 
            c*np.sqrt(1 / (3 * 3 * 320)))

**Comment by dialuser** [comment]
I also have a question on the step parameter of PhyCRNet class. In your demo, you used 1000. What if the model is so big that not all data can fit into a single batch.

Thanks.

**Comment by paulpuren** [comment]
> Hi Thanks for sharing the code. What's the rationale for using this uniform range? What do the numbers 3,3,20 represent?
> 
> module.weight.data.uniform_(-c_np.sqrt(1 / (3 * 3 * 320)), c_np.sqrt(1 / (3 * 3 * 320)))

Hi,

Thank you for you question. The reason why we use such uniform range is that we try to start with small numbers (close to zeros) and then gradually learn the dynamical propagation. The scientific computing problems are different from the general AI tasks. The traditional Xavier and He approaches will pose a tougher initialization for our problem, especially without any labeled data.   

Our initialization method is similar to Xavier Initialization. The only difference is that we have a small weighting coefficient to make the initialized weights close to zeros. In the previous code, 3 is the filter size, and 320 is the multiple of the channel number (e.g., 32). We have modified it to a more general version (see function ```initialize_weights```).

**Comment by dialuser** [comment]
Hi Paul

Thank for the in-depth explanation. That's helpful.
