### ISSUE TITLE
Computational costs of numerical solver vs. surrogate

### ISSUE THREAD

**Issue by stwerner97** [isds-neu/PhyCRNet#5]
Hi,

one common argument to use surrogate models over numerical solvers is that the latter are more costly to use computational wise.

Did you compare the time to rollout the network against the time to solve e.g. the Burgers equation numerically once the network is fully trained? Unfortunately, I could not find such a comparison in the paper.

Thanks a lot!

**Comment by paulpuren** [comment]
> Hi,
> 
> one common argument to use surrogate models over numerical solvers is that the latter are more costly to use computational wise.
> 
> Did you compare the time to rollout the network against the time to solve e.g. the Burgers equation numerically once the network is fully trained? Unfortunately, I could not find such a comparison in the paper.
> 
> Thanks a lot!

This is a good question. We didn't put the comparison of inference time in the paper, which we should have done. But I do compare with the high-order finite difference method on 2D Burgers equations with Reynolds number of 200. Our inference time is 4.09e-3 sec/step, while FD method has the simulation time of 4.19e-2 sec/step. I believe the discrepancy will become larger when the Renolds number increases. Hope this answer your question. Thank you.

**Comment by stweigand97** [comment]
Thanks a lot!
